server:
  port: 7779
spring:
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, nikki
      routes:
        - id: api_route
          uri: http://localhost:7778
          predicates:
            - Path=/api/**
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: 22223
  registery:
    id: nacos-registry
    address: nacos://localhost:8848